export const REGISTER = "REGISTER"
export const SELECT_SEAT = "SELECT_SEAT"
export const DESELECT_SEAT = "DESELECT_SEAT"
export const CANCEL_SEAT = "CANCEL_SEAT"
export const BOOK_SEAT = "BOOK_SEAT"
export const RESET = "RESET"
